version: "2"

services:
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx:/var/log/nginx
      - ./www:/var/www/app
    links:
      - php

  php:
#    image: php:fpm
    volumes:
      - ./www:/var/www/app
    build: ./images/php
    working_dir: /war/www/app
    links:
      - mysql

  mysql:
    image: mysql
    ports:
      - "3307:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
#      MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    links:
      - mysql
    ports:
      - 8001:80
    environment:
      PMA_HOST: mysql
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
#      MYSQL_ROOT_PASSWORD: root